name: Development Builds

on: [push, pull_request]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build 1.17+
        run: ./gradlew build
      - name: Build 1.14.4 - 1.16.5
        run: ./gradlew build -Dbuild16=true
      - uses: actions/upload-artifact@v2
        with:
          name: Compiled artifacts for ${{ github.sha }}
          path: |
            fabric/build/libs
            forge/build/libs
